In [1]:
import os
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv('/home/pramit67/HOGtrain.csv',delimiter='\t')
print(df)
df=df.fillna(0)


            F1        F2        F3        F4        F5      F6  category
0     0.051118  0.000000  0.032757  0.093885  0.069411  0.0223        10
1     0.048739  0.028780  0.022716  0.034183  0.031309  0.0480         9
2     0.051118  0.000000  0.032757  0.093885  0.069411  0.0223         9
3     0.000000  0.000000  0.000000  0.009848  0.010914  0.0057         2
4     0.022371  0.007782  0.027074  0.004240  0.008708  0.0076        12
...        ...       ...       ...       ...       ...     ...       ...
1198  0.049687  0.010986  0.007481  0.028120  0.038606  0.0186        12
1199  0.058648  0.026149  0.048838  0.020090  0.029494  0.0150        12
1200  0.045373  0.024791  0.025915  0.040138  0.041657  0.0318        12
1201  0.019282  0.015198  0.012674  0.003577  0.005563  0.0002        12
1202  0.049541  0.029570  0.031483  0.060845  0.060958  0.0189        12

[1203 rows x 7 columns]


In [3]:
df1=pd.read_csv('/home/pramit67/HOGtest.csv',delimiter='\t')
print(df1)
df1=df1.fillna(0)

           F1        F2        F3        F4        F5        F6  category
0    0.051118  0.000000  0.032757  0.093885  0.069411  0.022395         2
1    0.048739  0.028780  0.022716  0.034183  0.031309  0.048078        10
2    0.051118  0.000000  0.032757  0.093885  0.069411  0.022395         9
3    0.000000  0.000000  0.000000  0.009848  0.010914  0.005797         9
4    0.022371  0.007782  0.027074  0.004240  0.008708  0.007659         2
..        ...       ...       ...       ...       ...       ...       ...
198  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000        14
199  0.051118  0.000000  0.032757  0.093885  0.069411  0.022395        14
200  0.051118  0.000000  0.032757  0.093885  0.069411  0.022395        14
201  0.040437  0.019966  0.012179  0.011332  0.006346  0.009844        14
202  0.039520  0.017473  0.090387  0.014831  0.014865  0.012408        14

[203 rows x 7 columns]


In [4]:
X_train=df.drop('category',axis=1)
y_train=df['category']
X_test=df1.drop('category',axis=1)
y_test=df1['category']

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn.svm import SVC 
model = SVC(kernel='rbf',gamma=6.2,C=8.87,probability=True)
from sklearn.model_selection import train_test_split  
    
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=42) 


model.fit(X_train,y_train)

#Predict Output
predicted= model.predict(X_test) # 0:Overcast, 2:Mild
#    print(predicted)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score

print('MCC boosting',matthews_corrcoef(y_test,predicted)) 
print('Accuracy score boosting',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity macro boosting',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity macro ',specificity_score(y_test,predicted,average='micro'))

Using TensorFlow backend.


MCC boosting 0.0
Accuracy score boosting 26
Sensitivity micro boosting 0.12807881773399016
Specificity macro boosting 0.9
Sensitivity micro boosting 0.1
Specificity macro  0.90311986863711


/home/pramit67/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:872: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


# from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import BaggingClassifier
from sklearn.neural_network import MLPClassifier
model = BaggingClassifier(base_estimator= MLPClassifier(hidden_layer_sizes=(2,3,3)),n_estimators=3)
from sklearn.model_selection import train_test_split  
    
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0) 


model.fit(X_train,y_train)

#Predict Output
predicted= model.predict(X_test) # 0:Overcast, 2:Mild
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score
print('confusion matrix bagging',confusion_matrix(y_test,predicted))
print('classification report bagging',classification_report(y_test,predicted))
print('MCC bagging',matthews_corrcoef(y_test,predicted)) 
print('Accuracy score bagging',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity micro bagging',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity macro bagging',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity micro bagging',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity macro ',specificity_score(y_test,predicted,average='micro'))

In [6]:
from sklearn.ensemble import GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(n_estimators=20, max_features=2, max_depth=4, random_state=0)
gb_clf.fit(X_train, y_train)
#joblib.dump(gb_clf, '/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/GradienBoosting.pkl')

predicted= gb_clf.predict(X_test) # 0:Overcast, 2:Mild
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score

print('MCC boosting',matthews_corrcoef(y_test,predicted)) 
print('confusion matrix boosting',confusion_matrix(y_test,predicted))
print('classification report boosting',classification_report(y_test,predicted))
print('Accuracy score boosting',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity macro boosting',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity macro ',specificity_score(y_test,predicted,average='micro'))

MCC boosting -0.014966112327191144
confusion matrix boosting [[ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  3  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  1 17  3  1  0  0  1]
 [ 0  0  0  0  0  1  1  0  0 17  6  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  2  4  0  0  0  0]
 [ 2  0  1  0  1  1  0  1  0 38 22  2  0  0  0]
 [ 0  1  1  0  0  0  0  0  0  3  5  0  1  0  0]
 [ 0  0  2  1  0  1  0  0  1 31 14  1  0  0  0]]
classification report boosting               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         0
           2       0.00 

/home/pramit67/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/pramit67/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/pramit67/anaconda3/lib/python3.7/site-packages/imblearn/metrics/_classification.py:241: UndefinedMetricWarning: Sensitivity is ill-defined and being set to 0.0 in labels with no true samples.
  average, warn_for)


In [8]:
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)
predicted=model.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score
print('confusion matrix RF',confusion_matrix(y_test,predicted))
print('classification report RF',classification_report(y_test,predicted))
print('MCC RF',matthews_corrcoef(y_test,predicted)) 
print('Accuracy RF',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity RF',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity RF',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity RF',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity RF ',specificity_score(y_test,predicted,average='micro'))

confusion matrix RF [[ 0  0  0  0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  3  0  4  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  1 14  5  1  1  0  1]
 [ 1  2  0  1  1  0  0 15  5  0  0  0  1]
 [ 0  0  0  0  0  0  0  3  3  0  0  0  0]
 [ 2  0  0  0  0  1  0 34 27  2  2  0  0]
 [ 0  1  0  0  0  0  0  3  6  0  1  0  0]
 [ 0  2  1  1  0  0  0 25 21  1  0  0  0]]
classification report RF               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00        11
           3       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         1
           8       0.00      

/home/pramit67/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/pramit67/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/home/pramit67/anaconda3/lib/python3.7/site-packages/imblearn/metrics/_classification.py:241: UndefinedMetricWarning: Sensitivity is ill-defined and being set to 0.0 in labels with no true samples.
  average, warn_for)
