In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pickle
from scipy.cluster.vq import kmeans, vq
from skimage import feature

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip3 uninstall opencv-python
!pip3 uninstall opencv-contrib-python

Uninstalling opencv-contrib-python-4.1.2.30:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/opencv_contrib_python-4.1.2.30.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled opencv-contrib-python-4.1.2.30


In [ ]:
## pip install opencv-contrib-python 
!pip3 install opencv-python==3.4.2.16
!pip3 install opencv-contrib-python==3.4.2.16

     |████████████████████████████████| 25.0MB 1.3MB/s 
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
     |████████████████████████████████| 30.6MB 160kB/s 


In [ ]:
import matplotlib.pyplot as plt
import cv2

In [ ]:
import numpy as np
import cv2
import os
import re
import imutils
import pandas as pd
from skimage import feature
from sklearn.svm import SVC 
import pickle
numbers = re.compile(r'(\d+)')
def numericalSort(value):
    parts = numbers.split(value)
    parts[1::2] = map(int, parts[1::2])
    return parts
IMG_DIR = '/content/drive/My Drive/Data/tt_train/'
IMG_DIR1='/content/drive/My Drive/Data/tt_test/'
count=0
data1=pd.read_csv('/content/drive/My Drive/Data/tt-train.csv')
data3=pd.read_csv('/content/drive/My Drive/Data/tt-test.csv')
labels=data1['Category']
filenames=list(os.listdir(IMG_DIR))
filenames1=list(os.listdir(IMG_DIR1))
print(filenames)
filenames=sorted(filenames,key=numericalSort)
filenames1=sorted(filenames1,key=numericalSort)
data=[]
data2=[]

['31.png', '2743.png', '2089.png', '46.png', '2107.png', '2101.png', '2096.png', '2112.png', '2106.png', '2076.png', '2773.png', '2117.png', '2781.png', '2768.png', '2118.png', '2769.png', '2780.png', '6.png', '27.png', '2103.png', '2075.png', '2761.png', '23.png', '2778.png', '22.png', '2734.png', '2776.png', '2764.png', '43.png', '2767.png', '19.png', '2110.png', '2737.png', '38.png', '2.png', '25.png', '41.png', '2115.png', '1.png', '48.png', '2077.png', '2747.png', '2079.png', '2099.png', '2071.png', '2080.png', '2105.png', '2090.png', '4.png', '30.png', '2741.png', '26.png', '12.png', '2766.png', '20.png', '44.png', '21.png', '2757.png', '2088.png', '2092.png', '2777.png', '42.png', '2083.png', '2100.png', '2733.png', '45.png', '2084.png', '10.png', '2759.png', '2756.png', '2774.png', '2739.png', '2093.png', '2755.png', '35.png', '2098.png', '2102.png', '2738.png', '2763.png', '2735.png', '32.png', '17.png', '33.png', '8.png', '2120.png', '15.png', '2775.png', '2751.png', '9.png',

In [ ]:
desc_list_train=[]
desc_list_test=[]
for img in filenames:
    image = cv2.imread(os.path.join(IMG_DIR,img),0)
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints_sift,desc= sift.detectAndCompute(image, None)
    if len(keypoints_sift)>0:
        desc_list_train.append(desc) 
desc_list=np.array(desc_list)
for img in filenames1:
    image = cv2.imread(os.path.join(IMG_DIR1,img),0)
   # image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints_sift,desc= sift.detectAndCompute(image, None)
    if len(keypoints_sift)>0:
        desc_list_test.append(desc) 
    

In [ ]:
desc_float_train=[]
desc_float_test=[]
for i in range(0,len(desc_list_train)):
    for item in desc_list_train[i]:
        desc_float_train.append(item)
for i in range(0,len(desc_list_test)):
    for item in desc_list_test[i]:
        desc_float_test.append(item)

In [ ]:
desc_float_train=np.array(desc_float_train)
desc_float_test=np.array(desc_float_test)

In [ ]:
desc_float_train.shape
desc_float_test.shape

(23338, 128)

In [ ]:
desc_list_train=np.array(desc_list_train)
desc_list_test=np.array(desc_list_test)

In [ ]:
desc_list_train.shape
desc_list_test.shape

(60,)

In [ ]:
# clustering sift features 

In [ ]:
k = 150
vocab, var = kmeans(desc_float_train, k, 1) 
sz=len(data1)
features = np.zeros((sz, k), "float32")
for i in range(sz-2):
    words, distance = vq(desc_list_train[i],vocab)
    for w in words:
        features[i][w] += 1

In [ ]:
arr1=np.empty(shape=(0,150))

In [ ]:
arr1=np.concatenate([arr1,features])

In [ ]:
k = 50
vocab, var = kmeans(desc_float_test, k, 1) 
sz=len(data3)
features = np.zeros((sz, k), "float32")
for i in range(sz-1):
    words, distance = vq(desc_list_test[i],vocab)
    for w in words:
        features[i][w] += 1

In [ ]:
arr2=np.empty(shape=(60,100))

In [ ]:
arr2=np.concatenate([arr2,features],axis=1)

In [ ]:
arr2=np.array(arr2)
arr2.shape
#X_test=np.concatenate((arrt,arr2),axis=1)

(60, 150)

In [ ]:
X_train=arr1
X_test=arr2

In [ ]:
X_test.shape

(60, 150)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sscaler=StandardScaler()

In [ ]:
#X_test = sscaler.fit_transform(X_test)
X_train= sscaler.fit_transform(X_train)

In [ ]:
from sklearn import svm

In [ ]:
clf = svm.SVC(kernel='linear')

In [ ]:
print(X_train)

[[ 0.26539344  1.41395     0.24209532 ...  1.06734313 -0.55074724
   0.18233124]
 [ 0.26539344  4.66856637  3.82237827 ... -0.10556141  0.85422021
   1.82331239]
 [ 0.26539344  3.04125818 -0.78084266 ... -0.10556141  0.01123974
   2.37030611]
 ...
 [-0.35662243  0.87151394  5.35678525 ... -0.10556141  0.01123974
   0.18233124]
 [-0.9786383  -0.75579425 -0.78084266 ... -0.69201368 -1.11273422
  -0.9116562 ]
 [-0.9786383  -0.75579425 -0.78084266 ... -0.69201368 -1.11273422
  -0.9116562 ]]


In [ ]:
clf.fit(X_train,data1['Category'])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
predicted=clf.predict(X_test)
with open('/content/drive/My Drive/Data/SIFT.csv','ab')as f:
  np.savetxt(f,predicted,delimiter=',')

In [ ]:
y_test=data3['Category']
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score
print('confusion matrix SVM',confusion_matrix(y_test,predicted))
print('classification report SVM',classification_report(y_test,predicted))
print('MCC SVM',matthews_corrcoef(y_test,predicted)) 
print('Accuracy SVM',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity SVM',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity SVM',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity SVM',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity SVM ',specificity_score(y_test,predicted,average='micro'))
with open( '/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/SVM_SIFT.pkl','wb')as F:
  pickle.dump(ans,F)

confusion matrix SVM [[ 0 20  0]
 [ 0 19  1]
 [ 0 17  3]]
classification report SVM               precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.34      0.95      0.50        20
           2       0.75      0.15      0.25        20

    accuracy                           0.37        60
   macro avg       0.36      0.37      0.25        60
weighted avg       0.36      0.37      0.25        60

MCC SVM 0.11572751247156894
Accuracy SVM 22
Sensitivity SVM 0.36666666666666664
Specificity SVM 0.6833333333333332
Sensitivity SVM 0.36666666666666664
Specificity SVM  0.6833333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_test=data3['Category']
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import BaggingClassifier
from sklearn.neural_network import MLPClassifier
model = BaggingClassifier(base_estimator= MLPClassifier(hidden_layer_sizes=(2,3,3)),n_estimators=3)
from sklearn.model_selection import train_test_split 

In [ ]:
model = RandomForestClassifier(n_estimators=100)

In [ ]:
model.fit(X_train,data1['Category'])
predicted=clf.predict(X_test)
with open('/content/drive/My Drive/Data/SIFTRF.csv','ab')as f:
  np.savetxt(f,predicted,delimiter=',')

In [ ]:
y_test=data3['Category']
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score
print('confusion matrix RF',confusion_matrix(y_test,predicted))
print('classification report RF',classification_report(y_test,predicted))
print('MCC RF',matthews_corrcoef(y_test,predicted)) 
print('Accuracy RF',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity RF',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity RF',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity RF',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity RF ',specificity_score(y_test,predicted,average='micro'))
with open( '/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/RF_SIFT.pkl','wb')as F:
  pickle.dump(ans,F)

confusion matrix RF [[ 0 20  0]
 [ 0 19  1]
 [ 0 17  3]]
classification report RF               precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.34      0.95      0.50        20
           2       0.75      0.15      0.25        20

    accuracy                           0.37        60
   macro avg       0.36      0.37      0.25        60
weighted avg       0.36      0.37      0.25        60

MCC RF 0.11572751247156894
Accuracy RF 22
Sensitivity RF 0.36666666666666664
Specificity RF 0.6833333333333332
Sensitivity RF 0.36666666666666664
Specificity RF  0.6833333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

from sklearn.ensemble import GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(n_estimators=20, max_features=2, max_depth=4, random_state=0)
gb_clf.fit(X_train, data1['Category'])
#joblib.dump(gb_clf, '/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/GradienBoosting.pkl')

predicted= gb_clf.predict(X_test) # 0:Overcast, 2:Mild
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score

print('MCC boosting',matthews_corrcoef(y_test,predicted)) 
print('confusion matrix boosting',confusion_matrix(y_test,predicted))
print('classification report boosting',classification_report(y_test,predicted))
print('Accuracy score boosting',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity macro boosting',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity micro boosting',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity macro ',specificity_score(y_test,predicted,average='micro'))


with open('/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/Boosting.pkl','wb') as ifp:
  pickle.dump(gb_clf,ifp)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


MCC boosting 0.0
confusion matrix boosting [[ 0 20  0]
 [ 0 20  0]
 [ 0 20  0]]
classification report boosting               precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.33      1.00      0.50        20
           2       0.00      0.00      0.00        20

    accuracy                           0.33        60
   macro avg       0.11      0.33      0.17        60
weighted avg       0.11      0.33      0.17        60

Accuracy score boosting 20
Sensitivity micro boosting 0.3333333333333333
Specificity macro boosting 0.6666666666666666
Sensitivity micro boosting 0.3333333333333333
Specificity macro  0.6666666666666666


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import BaggingClassifier
from sklearn.neural_network import MLPClassifier
model = BaggingClassifier(base_estimator= MLPClassifier(hidden_layer_sizes=(2,3,3)),n_estimators=3)
from sklearn.model_selection import train_test_split  
    
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0) 


model.fit(X_train,data1['Category'])

#Predict Output
predicted= model.predict(X_test) # 0:Overcast, 2:Mild
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,matthews_corrcoef
from imblearn.metrics import sensitivity_score,specificity_score
print('confusion matrix bagging',confusion_matrix(y_test,predicted))
print('classification report bagging',classification_report(y_test,predicted))
print('MCC bagging',matthews_corrcoef(y_test,predicted)) 
print('Accuracy score bagging',accuracy_score(y_test,predicted,normalize=False))
print('Sensitivity micro bagging',sensitivity_score(y_test,predicted,average='micro'))
print('Specificity macro bagging',specificity_score(y_test,predicted,average='macro'))
print('Sensitivity micro bagging',sensitivity_score(y_test,predicted,average='macro'))
print('Specificity macro ',specificity_score(y_test,predicted,average='micro'))

with open('/content/drive/My Drive/SML_PROJECT/SML_MODEL_DATA/BaggingSIFT.pkl','wb') as ifp:
  pickle.dump(gb_clf,ifp)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


confusion matrix bagging [[ 0  0 20]
 [ 0  0 20]
 [ 0  0 20]]
classification report bagging               precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00        20
           2       0.33      1.00      0.50        20

    accuracy                           0.33        60
   macro avg       0.11      0.33      0.17        60
weighted avg       0.11      0.33      0.17        60

MCC bagging 0.0
Accuracy score bagging 20
Sensitivity micro bagging 0.3333333333333333
Specificity macro bagging 0.6666666666666666
Sensitivity micro bagging 0.3333333333333333
Specificity macro  0.6666666666666666


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:900: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
